### ISSUE TITLE
Publish to NuGet

### ISSUE THREAD

**Issue by smudge202** [microsoft/xunit-performance#100]
I admit, I have no idea what state the project is in right now (will clone and use a local build for now) but I can't see this on NuGet; any chance of a beta/pre-release build making it's way there?

**Comment by pharring** [comment]
@smudge202 it's in https://www.myget.org/gallery/dotnet-buildtools

e.g.:
https://www.myget.org/F/dotnet-buildtools/api/v2/package/Microsoft.DotNet.xunit.performance/1.0.0-alpha-build0026

Add this URL to your NuGet feeds:
https://www.myget.org/F/dotnet-buildtools/

**Comment by smudge202** [comment]
You're a boss, thanks @pharring . Was just starting to check out https://github.com/PerfDotNet/BenchmarkDotNet as an alternative.

I don't expect anything too much from an alpha, but wonder if there's a specific reason this hasn't made it to nuget.org yet. (i.e. Something I should be wary of?).

**Comment by ericeil** [comment]
The short version is that we have some internal policies at Microsoft that prevent publication of unsigned binaries on NuGet.  The eventual goal is to publish this on NuGet.

**Comment by smudge202** [comment]
No problems, thanks for help. I'll leave it to you guys to decide when to close the issue.

**Comment by luoyan0517** [comment]
@ericeil. We are considering to use xunit-performance as well. So may I know when are you targeting to have a RTM version and publish to nuget?

**Comment by RichiCoder1** [comment]
Consider myself interested in this too. This is a really good framework ya'll made.

**Comment by sjk07** [comment]
any update on this?

**Comment by deppe** [comment]
I was just looking for this as well. Any plan to move this to nuget?

**Comment by erick-thompson** [comment]
While I can add the feed to my dev box, the build systems assumes that packages come from nuget.org. Any update on when this might happen?

**Comment by adamsitnik** [comment]
@erick-thompson hello! I am not sure about the plans for NuGet.org, but I know how to overcome your problem with CI machine.

Whenever dotnet cli or VS restores packages it searches for per-solution and per-machine NuGet.config file. Per-machine can be found at `%HOMEPATH%\AppData\Roaming\Nuget\Nuget.Config ` on Windows and `/.nuget/NuGet/NuGet.Config` on Linux. You have most probably edited yours via VS, but your build systems don't have it.

To overcome this problem you need to create per-solution NuGet.config file and push it to your repository.

1. Save following file as `NuGet.config` in your solution folder (where you keep the `.sln` file)

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
	<add key="xunit-perf" value="https://www.myget.org/F/dotnet-buildtools/" />
  </packageSources>
</configuration>
```

2. Push it to your repo
3. Whenever you run dotnet restore the dotnet cli/VS will include this address in the search

**Comment by erick-thompson** [comment]
I was hoping to avoid this solution, but it will work. Thanks.

**Comment by cheenamalhotra** [comment]
A NuGet release would be so nice! Any plans in future to make this official?

**Comment by adamsitnik** [comment]
> A NuGet release would be so nice! Any plans in future to make this official?

Hi @cheenamalhotra 

As far as I know there are no such plans. .NET Team has switched to  https://github.com/dotnet/BenchmarkDotNet for micro benchmarks which can be found at https://github.com/dotnet/performance

**Comment by cheenamalhotra** [comment]
Thanks for the info, I will give BenchmarkDotNet a try!

**Comment by brianrob** [comment]
Closing prior to archive.
