### ISSUE TITLE
.NET 4.5 support

### ISSUE THREAD

**Issue by eriove** [Microsoft/xunit-performance#101]
How come there isn't any .NET 4.5 support, is it just that you don't need it or are there features missing in the framework?

I tried creating .NET 4.5 projects (see [this](https://github.com/eriove/xunit-performance) branch) but the XML-files generated are missing the `<iterations>` tags. If you don't know of any issues I might dig further into the problem.

**Comment by ericeil** [comment]
4.5 support isn't something we've needed yet.  I wouldn't be surprised if we've taken dependencies on 4.6-specific behavior, but I also wouldn't be surprised if that was totally unnecessary. :)

**Comment by eriove** [comment]
Ok. Then I'll try once more getting my changes to work.

**Comment by eriove** [comment]
I haven't had as much time as I would have liked but I'm now seeing the same problems with .NET 4.6 as with .NET 4.5. I'll create a new issue if I manage to pin down the problem.

**Comment by eriove** [comment]
I've now narrowed down my issues. They were unrelated to .NET 4.5 and I have created a new issue (#109) for the actual problem. I don't really need .NET 4.5 support anymore. Not sure what your process is like but you could probably close this issue.
