### ISSUE TITLE
running in xunit-perf in Windows 7.

### ISSUE THREAD

**Issue by robinson** [Microsoft/xunit-performance#105]
Hi,
When I am trying to run for collecting more detail by following command in Windows 7:
xunit.performance.run MyTests.dll -runner xunit.console.exe -runid MyRun1234
It occurs this error:
Error: Profile source only availabe on Win8 and beyond.
   by Microsoft.ProcessDomain.ProcDomain.<ExecuteAsync>d__26`1.MoveNext() in D:
\work station\projects\perf_test_dataexchange\xunit-performance-master\src\ProcD
omain\ProcDomain.cs:row 207.

**Comment by ericeil** [comment]
Did you apply any custom measurement attributes to your tests, or just the `[Benchmark]` attribute?

**Comment by robinson** [comment]
Hi Eric - I just re-run the example with the command above. Regards, Robin
