### ISSUE TITLE
Make .etl output as optional

### ISSUE THREAD

**Issue by luoyan0517** [Microsoft/xunit-performance#107]
The .etl file is large, and we do not want it most of times. For example, when the perf run is nightly, and we just want the xml output to analyze the trend.

**Comment by ericeil** [comment]
The data in the xml output comes from the .etl file, so we do need to generate it.  However, if you don't want to keep it, you can go ahead and delete it after the run.  Our team plans to keep the ETL files for as long as we have available storage, as they're very useful for diagnosing the causes of regressions, which can sometimes be hard to reproduce in another environment.
