### ISSUE TITLE
Need better error reporting if outdir does not exist.

### ISSUE THREAD

**Issue by eriove** [microsoft/xunit-performance#109]
When running on our build server no ETL file is created and an exception is thrown in  `ETWLogging.StartAsync()`. If I copy the dll with the tests (built on the build server) and the xunit.performance.run.exe with it dependencies to a directory on my local machine everything works as expected. My machine is running WIndows 8.1 and the build server Windows Server 2012 R2.

What should I do to continue investigate the issue? Where can the difference be?

Here's the stack trace:
`The system cannot find the path specified. (Exception from HRESULT: 0x80070003) [C:\Builds\3\Common components\AwtSG.CommonComponent.PerformanceTests\src\Common components\build\performancetests.proj]
            at Microsoft.ProcessDomain.ProcDomain.<ExecuteAsync>d__26``1.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at Microsoft.Xunit.Performance.ETWLogging.<StartAsync>d__4.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at Microsoft.Xunit.Performance.EtwPerformanceMetricLogger.StartLogging(ProcessStartInfo runnerStartInfo)
            at Microsoft.Xunit.Performance.ProgramCore.RunTests(XunitPerformanceProject project)
            at Microsoft.Xunit.Performance.ProgramCore.Run(String[] args)`

**Comment by eriove** [comment]
I found the issue. To input the search path to the `-outdir`  I had to add a space after the \ before the ". (Unfortunately we have a space in the path.)

By changing 
`arguments.Push(args[i]);`
to
`arguments.Push(args[i].Trim(' '));`
in `ProgramCore.ParseCommandLine()` the issue is resolved.

**Comment by ericeil** [comment]
I'm not sure I'd want to trim spaces off of the directory name; spaces in paths are valid, after all.  Can you explain the scenario that lead to the issue in a little more detail?

**Comment by eriove** [comment]
I didn't think of the case when a directory name ends with a space. I call the runner in the following way

`xunit.performance.run.exe "D:\Some folder with space\bin\MyProject.PerformanceTests.dll" -runid MyProject.PerformanceTests_20151112.3 -outdir "D:\Some folder with space\bin\ " -runner "D:\Some folder with space\tools\Xunit.Performance\xunit.console.exe"`

`D:\Some folder with space\bin\` is actually a variable that is re-used, hence the ending backslash in the outdir. If I omit the space before the " Windows argument parser (I'm not 100% if it's .NET or Windows) assumes I want to escape the " with the backslash which makes the arguments completely invalid.

Now that I know about the problem I can think of many ways to work around it, but it was a real pain to find it, especially when the exception is thrown in a different part of the code and it didn't occur on my local machine (I've no idea why it didn't throw there too).

**Comment by ericeil** [comment]
Thanks!  I'll leave this open for now, as a note to report this error in a better way.

**Comment by vancem** [comment]
The more serious issue here is that you should be allowed to do

-outdir "D:\Some folder with space\bin\"

on a command line.    The standard way of quoting “ on a windows command line is to repeat the quote  (thus “” becomes “).

However I suspect that on UNIX machines the \ is used to quote escapes.

My recommendation is that if we go with UNIX command line conventions, then we should allow / to act like a \ and encourage complete UNIX conventions.   Going half way is bad.

Eric: Do you know who owns the run.exe (and how it does command line parsing.

Vance

**Comment by ericeil** [comment]
Whatever translation happens with backslashes seems to happen before the managed Main method is called.  I just tried this simple program:

```csharp
using System;

namespace PrintArgs
{
    class Program
    {
        static void Main(string[] args)
        {
            foreach (var arg in args)
                Console.WriteLine(arg);
        }
    }
}
```
If I invoke it thusly (directly from the console):

```
> printargs hello "there\"
```

The output is:

```
hello
there"
```

If I "escape" the backslash, I get the desired result:

```
> printargs hello "there\\"
hello
there\
```

I'm not sure what xunit.performance.run can do, given that this translation seems to happen somewhere before Main is even called.

**Comment by vancem** [comment]
I agree that it is not xunit.performance.run’s issue.  How was that EXE generated?   I assume this is CoreCLR based, which imply it is an issue in CoreCLR (since it owns argument parsing).

Vance

**Comment by eriove** [comment]
I tried running this C++ program from [MSDN](https://msdn.microsoft.com/en-us/library/17w5ykft.aspx).
`
#include "stdafx.h"


#include <iostream>

using namespace std;
int main(int argc,      // Number of strings in array argv
	char *argv[],   // Array of command-line argument strings
	char *envp[])  // Array of environment variable strings
{
	int count;

	// Display each command-line argument.
	cout << "\nCommand-line arguments:\n";
	for (count = 0; count < argc; count++)
		cout << "  argv[" << count << "]   "
		<< argv[count] << "\n";
	return 0;
}
`

and had the same behavior:
`Debug>PrintArgs.exe hello "there"

Command-line arguments:
  argv[0]   PrintArgs.exe
  argv[1]   hello
  argv[2]   there

>PrintArgs.exe hello "there\"

Command-line arguments:
  argv[0]   PrintArgs.exe
  argv[1]   hello
  argv[2]   there"`

Hence it's a Windows and not a .NET/CoreCLR thing.

I would suggest to just give an error message if the outdir path doesn't exist. If the error message contains the path that was used it is easy to fix the problem for the user.

**Comment by brianrob** [comment]
Closing prior to archive.
