### ISSUE TITLE
Add a Warning for Non-Serializable MemberData - Tests Don't Run

### ISSUE THREAD

**Issue by khdang** [microsoft/xunit-performance#124]
When I use `MemberData` attribute with non-primitive type as return values such as an custom type, the perf tests don't get run and there is no perf result.

Here is the code I use:

``` csharp
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Runtime.Serialization;
using Microsoft.Xunit.Performance;
using Xunit;

namespace Tests
{
    public interface IPerformanceTestData
    {
        void RunTest();
    }

    public class TestData1 : IPerformanceTestData
    {
        public void RunTest()
        {
            long sum = 0;
            for (int i = 0; i < 1000; ++i)
                for (int j = 0; j < 1000; ++j)
                    sum += i + j;
        }

        public override string ToString()
        {
            return "TestData1";
        }
    }

    public class PerformanceTest
    {
        public static IEnumerable<object[]> MemberData()
        {
            yield return new object[] { new TestData1() };
        }

        [Benchmark]
        [MemberData(nameof(MemberData))]
        public void UnitTest(IPerformanceTestData testData)
        {
            foreach (var iteration in Benchmark.Iterations)
            {
                using (iteration.StartMeasurement())
                {
                    testData.RunTest();
                }
            }
        }
    }
}
```

Expectation: perf number is produced in -analysis.html
Actual: the -analysis.html file is empty

Am I missing anything? How do I use custom type with `MemberData` attribute?

**Comment by ericeil** [comment]
Does it work if you attribute `TestData1` with `[Serializable]`?

**Comment by khdang** [comment]
```SerializableAttribute``` is not available on CoreClr

**Comment by AndyAyersMS** [comment]
I ran into this too. Evidently xunit requires member data types to be xunit-serializable. See xunit/xunit#429. It would be nice if xunit-perf warned about this, since the reason for it is not obvious.

You can work around it by implementing your own serialization.

**Comment by brianrob** [comment]
This looks like an xunit limitation.  Having a warning seems reasonable.

**Comment by brianrob** [comment]
Closing prior to archive.
