### ISSUE TITLE
Need Automated Full Cross-Platform Build

### ISSUE THREAD

**Issue by brianrob** [Microsoft/xunit-performance#141]
CLI components are executables, but can only be built for an individual platform.  We want these CLI components to be available for all platforms, so we need to figure out how to build and package them appropriately.

**Comment by dsgouda** [comment]
@brianrob Cli components are not executables the way they are currently being built, however they do generate a dll with an entrypoint and still need to have the runtimes explicitly specified

**Comment by brianrob** [comment]
This is solved with the addition of xunit.performance.api.
