### ISSUE TITLE
Statistics computation assume that the distribution is normal

### ISSUE THREAD

**Issue by lt72** [microsoft/xunit-performance#147]
Statistics are computed under the assumption that the distribution is normal. Such assumption is questionable, especially for small populations, which is typically the case. 

Consider using a non-parametric estimation technique for metrics on populations, and some variant of hypothesis-based testing for determining if some metric is significantly different between populations.

**Comment by brianrob** [comment]
Next step: Consider options and make a proposal.

**Comment by brianrob** [comment]
Closing prior to archive.
