### ISSUE TITLE
Cannot specify number of iterations

### ISSUE THREAD

**Issue by lt72** [microsoft/xunit-performance#149]
TFS: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/219936?fullScreen=false

**Comment by brianrob** [comment]
Min and max iterations are hardcoded in the harness.

Next step: Propose a mechanism to specify min and max iterations if desired (likely per test).
Complexity: Medium

**Comment by brianrob** [comment]
Closing prior to archive.
