### ISSUE TITLE
Update README to Cover Aquisition of Xunit.Performance

### ISSUE THREAD

**Issue by KrzysztofCwalina** [microsoft/xunit-performance#152]
The readme talks about running tests using xunit.performance.run.exe, but does not say how to get the tool.

**Comment by AArnott** [comment]
All the tools and assemblies mentioned can only be built from source, it seems. I have several changes that I'm preparing to send PRs for to help resolve this. But my first PR hasn't been looked at yet.

**Comment by KrzysztofCwalina** [comment]
cc: @jonfortescue

**Comment by redknightlois** [comment]
Bump. Any news on this?

**Comment by lt72** [comment]
@brianrob: Brian owns this code base and can attend to the PR
@dsgouda: can you provide/point to the latest for acquiring the runner?

**Comment by brianrob** [comment]
Right now, the best way to acquire the runner is by building the source.  We are working to make the workflow simpler, but I expect it to take some time (e.g. post .NET Core 1.1).

**Comment by brianrob** [comment]
The preferred method to run is now using xunit.performance.api, which can be acquired via NuGet.  For an example, see https://github.com/Microsoft/xunit-performance/blob/master/tests/standalonesample/standalonesample.csproj.

Next step: Update the README.
Complexity: Simple

**Comment by brianrob** [comment]
Closing prior to archive.
