### ISSUE TITLE
Nuget package dependency on BuildTools is specified incorrectly

### ISSUE THREAD

**Issue by lukegeor** [Microsoft/xunit-performance#157]
Nuget package relies on Microsoft.DotNet.BuildTools.TestSuite version >= 1.0.0-prerelease-508-01. The format for the BuildTools nuget packages version is specified like this: 1.0.0-prerelease-00508-01. It is not allowing me to install the xunit-performance package because the version of BuildTools it's looking for is incorrectly specified.

![issue](https://cloud.githubusercontent.com/assets/8031102/16350542/2244a9b4-3a14-11e6-8e18-28b8e6e7c9c4.png)

**Comment by lukegeor** [comment]
I've added [PR 158](https://github.com/Microsoft/xunit-performance/pull/158) to address this issue.

**Comment by lt72** [comment]
@dsgouda 
Deepak, please check this and re-publish the package?

**Comment by dsgouda** [comment]
@lt72 Package 0039 should have fixed this can you verify please

**Comment by lukegeor** [comment]
I noticed this was fixed last week when we updated our Nuget package.
Commit 3d369212cd5022b5dfa9979527a30d42d8506d7c resolved the problem. Thank
you.

Luke
