### ISSUE TITLE
When running in console mode, it should run properly

### ISSUE THREAD

**Issue by redknightlois** [microsoft/xunit-performance#160]
Specially when you are running under the debugger to ensure your test is correct, there shouldnt be any failure.

For example I had to resort to:

``` csharp
public class BenchBase
    {
        protected void ExecuteBenchmark( Action action )
        {
            if ( Debugger.IsAttached )
            {
                action();
            }
            else
            {
                foreach (var iteration in Benchmark.Iterations)
                {
                    using (iteration.StartMeasurement())
                    {
                        action();
                    }
                }
            }
        }
    }
```

It could be great that you can have a `ConsoleIteration` running instead. If that is not possible a `NullIteration` at least so we dont get a `NullReferenceException`

**Comment by brianrob** [comment]
@redknightlois, can you tell me a bit more about the failure that you saw here?

**Comment by brianrob** [comment]
Closing prior to archive.
