### ISSUE TITLE
Need package compatible with latest xunit CLI support

### ISSUE THREAD

**Issue by AndyAyersMS** [Microsoft/xunit-performance#162]
The [recommended xunit for CLI release](http://xunit.github.io/docs/getting-started-dotnet-core.html) is not compatible with the latest preview release of xunit-performance.

This causes basic xunit testing to fail.

Running 'dotnet test' on a project with xunit-performance dependencies fails as follows:
```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 
'xunit.runner.utility.dotnet, Version=2.2.0.3300, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'. 
The located assembly's manifest definition does not match the assembly reference. 
(Exception from HRESULT: 0x80131040)
   at Xunit.Runner.DotNet.Program..ctor()
   at Xunit.Runner.DotNet.Program.Main(String[] args)
```

because the 1.0.0-prerelease-00508-1 version of xunit.runner.utility.dotnet is already loaded (via xunit-performance's dependence on DotNet.Build.Tools.TestSuite)

**Comment by AndyAyersMS** [comment]
@lt72, @redknightlois FYI

**Comment by redknightlois** [comment]
@AndyAyersMS that explains a lot.

**Comment by lt72** [comment]
@deshank

**Comment by dsgouda** [comment]
I believe @AndyAyersMS might be right here since we are referencing an older version of the xunit.runner.unitlity.dotnet dll when building our xunit performance tool here
https://github.com/Microsoft/xunit-performance/blob/master/src/xunit.performance.run.core.nuspec#L32

We have also noticed similar dependency issues where tests built referencing later versions of dependencies do not conform with perf tool's older dependencies (eg. System.Runtime) causing similar failures.

**Comment by lt72** [comment]
Let's fix this after you are done with your current task (ETA is today I believe) and, as you suggested yourself, let's also fix the bogus references here

https://github.com/Microsoft/xunit-performance/blob/master/src/xunit.performance.run.core.nuspec#L47  

and here

https://github.com/Microsoft/xunit-performance/blob/master/src/xunit.performance.nuspec#L57 

where '508-01' should be '00508-01'

**Comment by redknightlois** [comment]
Any idea when this is going to be released to the Build Tools Feed?

cc @dsgouda @lt72 @AndyAyersMS

**Comment by dsgouda** [comment]
@redknightlois I'm working on a fix for this break and should have it published in the next couple of days. Apologize for the delay.

**Comment by dsgouda** [comment]
@redknightlois Package 0040 published yesterday should fix the CoreFX perf test runs. Please take a look.
