### ISSUE TITLE
Would be nice to have CLI-friendlier version

### ISSUE THREAD

**Issue by AndyAyersMS** [Microsoft/xunit-performance#163]
For instance implementing a dotnet verb that launches tests in performance mode and then possibly analyzes the results.

**Comment by brianrob** [comment]
We now have a CLI-friendly way to run xunit.performance tests.  Documentation has yet to be updated, but #152 covers updating the README.  https://github.com/Microsoft/xunit-performance/tree/master/tests/standalonesample is a good example.
