### ISSUE TITLE
XML output writes test name instead of type in type field

### ISSUE THREAD

**Issue by DrewScoggins** [Microsoft/xunit-performance#185]
In the type field we use the entire name of the test rather then just the type.  This causes issues when parsing strings like this
`<test name="System.Tests.Perf_String.Split(s: &quot; àÀ&quot;, arr: ['1', 'a', ' ', '0', 'd', ...], options: RemoveEmptyEntries)" type="System.Tests.Perf_String.Split(s: &quot; àÀ&quot;, arr: ['1', 'a', ' ', '0', 'd', ...], options: RemoveEmptyEntries)" method="System.Tests.Perf_String.Split(s: &quot; àÀ&quot;, arr: ['1', 'a', ' ', '0', 'd', ...], options: RemoveEmptyEntries)" time="0.0076985073021867056">`

**Comment by brianrob** [comment]
@DrewScoggins, this is intentional because the method name is not enough to distinguish between tests when data is passed to the test as an argument.  Is there a bug here, or are you looking for something to simplify parsing the resulting XML?

**Comment by jorive** [comment]
I believe this is fixed.

**Comment by brianrob** [comment]
Ok, thanks @jorive.  @DrewScoggins, please re-open if this is not fixed.
