### ISSUE TITLE
Cleanup the API output file generation.

### ISSUE THREAD

**Issue by jorive** [microsoft/xunit-performance#188]
We need to unify the way output files are generated by the API (e.g it would be good to make sort a separate operation that occurs before writing to the csv, xml file generation occurs per assembly and markdown at the harness dispose, etc.)

**Comment by brianrob** [comment]
Right now, there is not a clean abstraction between generating results and writing them out.  This issue tracks designing and implementing the abstraction.

**Comment by brianrob** [comment]
Closing prior to archive.
