### ISSUE TITLE
Allow to measure managed heap allocations

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Microsoft/xunit-performance#198]
Core CLR now has APIs to measure GC allocations very precisely:

namespace System
{
    public static class GC
    {
        public long GetAllocatedBytesForCurrentThread();
        public long GetAllocatedBytesForThread(int managedThreadId);
    }
}

It would be great if xunit perf allowed to add such measurement to benchmarks.

**Comment by jorive** [comment]
@KrzysztofCwalina I'm currently working into adding this metric. It will be in the next release of the API :)

**Comment by jorive** [comment]
Closing this issue as the metric as added to the API with #204
