### ISSUE TITLE
Add the ability to group test results

### ISSUE THREAD

**Issue by KrzysztofCwalina** [microsoft/xunit-performance#199]
It would be great to be able to group tests and metrics and show deltas between them. 

For example, let's say there are 4 tests: A, B, C, D. I would like to indicate that A and B are in one group and C and D in another. A and D would be marked as "baseline"

The summary table would show items in each group next to each other a sub group by "metric", and showing deltas between one test marked as "baseline" and the rest. BenchmarkDotNet does it quite nicely.

e.g.

Test A Duration    100     100%
Test B Duration    110      110%

Test A Instructions Retired 300K 100%
Test B Instructions Retired 200K  66%

Test C Duration    100     89%
Test D Duration    110      100%

Test C Instructions Retired 300K 150%
Test D Instructions Retired 200K  100%

**Comment by brianrob** [comment]
Closing prior to archive.
