### ISSUE TITLE
The ability to compare two branches

### ISSUE THREAD

**Issue by KrzysztofCwalina** [microsoft/xunit-performance#201]
During development it's often super useful to compare before and after results. It would be great if the harness allowed that. Here is how I imagine the basic scenario:
1. Switch to "before" git branch
2. Run benchmarks with a flag --baseline <name>
3. Switch to "after" git branch
4. Run the same benchmarks with a flag --compare <name>
5. The harness outputs results (both detailed files and summary table) showing the deltas between baseline and the second run.

**Comment by brianrob** [comment]
Closing prior to archive.
