### ISSUE TITLE
Remove Xunit-Performance Runner from the master branch

### ISSUE THREAD

**Issue by jorive** [Microsoft/xunit-performance#206]
We need to remove the xunit-performance runner from the master branch because it is considered deprecated. This change is in favor to the xunit-performance-api which is actively being developed to support benchmarking .NET core and full framework.

The old runner has been moved to the branch origin/1.0.0-alpha, where bug fixes and servicing will be done.

In addition, we need to change the versioning of the API from alpha-build00xx to beta-build000x to avoid conflicts with releases of the two branches.

**Comment by brianrob** [comment]
Sounds good.  Thanks @jorive.

**Comment by jorive** [comment]
This was done a while back (old runner moved to a different branch to allow bug fixes to old users).
