### ISSUE TITLE
Have a Mode to Allow Tests to Run Without ETW

### ISSUE THREAD

**Issue by billwert** [Microsoft/xunit-performance#211]
It would be nice if the harness had a fallback or option to not require administrator. For simple benchmarking this would suffice and would lower the friction to get started.

**Comment by billwert** [comment]
@brianrob not sure how you want to handle this, but I think a better title for this would be "mode for not using xperf". I was going to open another issue and recalled this one. Thoughts?

**Comment by brianrob** [comment]
@billwert sounds good to me.

@jorive, I think you're already looking into this...

**Comment by jorive** [comment]
@billwert @brianrob Coming Soon! Stay tuned! :)

**Comment by jorive** [comment]
This is already fixed.
