### ISSUE TITLE
stopall command

### ISSUE THREAD

**Issue by billwert** [microsoft/xunit-performance#217]
It would be nice if the harness had a -stopall command for trying to stop any ETW session it is capable of starting. I've hit it a couple times where I'll have a crash or ctrl-c and leave sessions going.

(Unrelated: Do we have a ctrl-c handler? Adding one that shuts down sessions would be slick if we don't.)

**Comment by jorive** [comment]
@billwert We do have in place Ctrl-C, Ctrl-Break, and closing the console window handler. The only case where I've seen it not clean up properly is when terminating the process. Could you please tell me the version of the API that you are using, and a repro case. If this is still failing on the current build, then it is a bug and I would like to look into it.

**Comment by billwert** [comment]
I don't have a great repro. I was playing around with writing / running some tests and wound up with 750GB of ETLs on my machine. :) Working with it today I can't get it to misbehave badly. 

Regardless, I think ETW tooling should have something like PerfView's abort command so that the user can be confident that they have shut everything down. That's what I'd like to see here.

**Comment by brianrob** [comment]
Closing prior to archive.
