### ISSUE TITLE
Increase PMC reload interval for InstructionsRetired

### ISSUE THREAD

**Issue by AndyAyersMS** [Microsoft/xunit-performance#229]
Current PMC reload value for instructions retired is 100,000 which results in roughly one interrupt per 0.1 ms of execution and one ETL even per interrupt per core (from what I can see). So most ETL's are dominated by these samples.

Seems like we could run with a value 10x or 20x higher without increasing the noise floor dramatically, and cut the size of ETL by similar factors.

Worth an experiment, anyways.

**Comment by jorive** [comment]
@AndyAyersMS This change was pushed to the API in recent versions. We increased the sampling from 100,000 to 1,000,000.

**Comment by jorive** [comment]
Issue was fixed with https://github.com/Microsoft/xunit-performance/pull/241
