### ISSUE TITLE
Any way to get callbacks on benchmark events?

### ISSUE THREAD

**Issue by AndyAyersMS** [microsoft/xunit-performance#237]
When running in stopwatch mode it is sometimes useful to run the entire benchmark process under some other profiler -- for instance so we can take a deeper look at microarchitectural issues.

It would be useful to be able to register callbacks for various benchmark-related events so that the other profiler can be notified about the identity and extent of the timed regions of execution.

**Comment by pharring** [comment]
There's already an BenchmarkEventSource. Would that do for you?

https://github.com/Microsoft/xunit-performance/blob/a59cafba37389c004dd922c56065e475cbb41821/src/xunit.performance.execution/BenchmarkTestInvoker.cs#L43

**Comment by jorive** [comment]
When you run with the `stopwatch` option, we do not turn on ETW, so the markers are not going to be there when running under `PerfView`. This option was meant to have a lean measurement of benchmark time without the overhead of ETW.

**Comment by AndyAyersMS** [comment]
@jorive An example use case would be running the benchmark under vtune. I'd like to use xunit-perf to orchestrate execution, but add a way to call back into vtune around each benchmark and iteration, so vtune can create markers in its own format and subsequently one can correlate xunit-perf measured intervals with the measurements vtune makes.

@pharring that might work, I'll take a look.

**Comment by brianrob** [comment]
Closing prior to archive.
