### ISSUE TITLE
I don't see the Benchmark test method at "Test Explorer"

### ISSUE THREAD

**Issue by pavenkostanislav** [Microsoft/xunit-performance#250]
When I push "Run All" I don't see my created method with attribute "Benchmark"
Could you help me quick started?

**Comment by jorive** [comment]
@pavenkostanislav Could you please share the benchmarks source code and project? Could it be that the method marked as `[Benchmark]` is private?

**Comment by jorive** [comment]
@pavenkostanislav ping

**Comment by jorive** [comment]
@pavenkostanislav ping

**Comment by jorive** [comment]
Hi @pavenkostanislav , 

There has not been any response since the issue was opened, we do not know if this is still an issue, and we do not have a repro case. This is why I am closing this issue.

Please feel free to reopen it with more information, or open a new one.

Thanks,

-José
