### ISSUE TITLE
VSTS task to get reports

### ISSUE THREAD

**Issue by fleed** [Microsoft/xunit-performance#253]
Is there a VSTS task to get performance reports and ideally figuring out if there are variations?
What is the suggested way to create a graph measuring performance over multiple runs? I'm quite sure that Microsoft has something internally (maybe together with PowerBI?).

Any tutorial/documentation/starting point to create something like this?

Thank you

**Comment by jorive** [comment]
@fleed Your question would more appropriate in any of the links below: https://developercommunity.visualstudio.com/spaces/21/index.html
https://github.com/Microsoft/vsts-tasks
