### ISSUE TITLE
XunitPerformanceHarness prints unwanted Console output

### ISSUE THREAD

**Issue by noahfalk** [microsoft/xunit-performance#260]
Issue ported from comments in https://github.com/dotnet/coreclr/pull/16353:

> XunitPerformanceHarness has hard-coded console writeline usage inside it and I wanted all that output spew in a file to keep the console output clearer. I wound up hijacking Console.Out whenever using XunitPerformanceHarness in order to capture and redirect the logging.

Repro:
Write code such as...

    using(var harness = new XunitPerformanceHarness(args))
    {
        harness.RunScenario(...)
    }

Goal: Provide someway to redirect the console logging this does into a stream, or ideally a callback
Actual: Output will be written to the console

**Comment by hack2root** [comment]
You can  redirect the console logging manuallyb y using cmd.exe > operator

**Comment by jzabroski** [comment]
@noahfalk  Why doesn't Xunit.Performance just use ITestOutputHelper abstraction in Xunit core for tests, and IMessageSink for general purpose output?

https://xunit.github.io/docs/capturing-output

**Comment by noahfalk** [comment]
@jzabroski - I wasn't the person who wrote xunit.performance so I can't give a definitive answer why the authors made particular design choices. I can say that in my use-case I wasn't using this library from an xunit test so if the authors had done that it would have made it a little awkward for me.

**Comment by brianrob** [comment]
Closing prior to archive.
