### ISSUE TITLE
did we lose xunit pass-through options?

### ISSUE THREAD

**Issue by AndyAyersMS** [microsoft/xunit-performance#265]
We used to be able to pass options through to xunit, for instance to filter tests based on class name and/or method name (syntax was `-class className` and `-method methodName` respectively.

Is there still some way to do this? If so, can we document it? If not, can we please add it back? Otherwise working with perf assemblies with many embedded benchmarks is painful.

**Comment by jorive** [comment]
I do not remember those options since this project became an API, but they can certainly be added. The only option there is right now is `--perf:typenames`, which you probably already tried.

**Comment by brianrob** [comment]
Closing prior to archive.
