### ISSUE TITLE
Improper cleanup of ETL files

### ISSUE THREAD

**Issue by DrewScoggins** [Microsoft/xunit-performance#272]
On lab machines during CoreFX runs we will occasionally start to see errors like this. I investigated this and the problem is that the System process is still holding a handle to an ETL file in that workspace. When we then try to delete the workspace we can't because that handle prevents deletion. We need to do a better job of cleaning up our ETL sessions in xunit-performance.

@billwert @brianrob 

```ERROR: [WS-CLEANUP] Cannot delete workspace: remote file operation failed: C:\J\w\perf_windows_---356c2fc4 at hudson.remoting.Channel@7fecbfe2:JNLP4-connect connection from 131.107.147.138/131.107.147.138:5616: java.io.IOException: Unable to delete 'C:\J\w\perf_windows_---356c2fc4\artifacts\bin\tests\System.Text.Encoding.Performance.Tests\netcoreapp-Windows_NT-Release-x64'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.```

**Comment by jorive** [comment]
@DrewScoggins Could you please give more details on the run. Did the run timed out? Was the process killed? Generally, these issues where the ETW session stays open occurs when those two cases occur and the application is not given the chance to exit gracefully. In those cases, you will need to stop the open sessions, or reboot the machine.

**Comment by DrewScoggins** [comment]
It is unclear why it happened. It could have been a timeout it could have been a crash. Regardless, we need to make the process more resilient to this kind of failure. I could believe that this is not the right place to do it and we should do the checking for closed sessions at a higher level in the stack, but the answer being manual intervention on the machines is not good enough.

**Comment by jorive** [comment]
Just to be clear, I was suggesting for manual intervention. Automation should know how to reboot machines, or you could add an extra tool to automation to query for providers, and stop sessions that are holding files on that folder.

**Comment by jorive** [comment]
Without more information this issue seems external.

**Comment by DrewScoggins** [comment]
Yeah, I can agree with moving this issue to both coreclr and corefx to track how we handle this outside of the tool. Let me do that and then I will close this issue.

**Comment by DrewScoggins** [comment]
https://github.com/dotnet/corefx/issues/33535
