### ISSUE TITLE
XUnitPerformanceHarness.RunBenchmarks Exception "The specified module could not be found"

### ISSUE THREAD

**Issue by jzabroski** [microsoft/xunit-performance#273]
```
System.ComponentModel.Win32Exception (126): The specified module could not be found
   at Microsoft.Diagnostics.Tracing.Extensions.ETWKernelControl.LoadKernelTraceControl()
   at Microsoft.Diagnostics.Tracing.Extensions.ETWKernelControl.Merge(String[] inputETLFileNames, String outputETLFileName, EVENT_TRACE_MERGE_EXTENDED_DATA flags)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.MergeInPlace(String etlFileName, TextWriter log)
   at Microsoft.Xunit.Performance.Api.ETWProfiler.Record(XUnitPerformanceSessionData xUnitPerformanceSessionData, XUnitPerformanceMetricData xUnitPerformanceMetricData, Action action)
   at Microsoft.Xunit.Performance.Api.XunitPerformanceHarness.RunBenchmarks(String assemblyFileName)
   at JohnZabroski.Xunit.Performance.Runner.Program.Main(String[] args) in D:\source\JohnZabroski.Xunit.Performance.Runner\Program.cs:line 15}
```

This appears to be related to #255 

I think a big problem is how the package is put together.

Here is what I did:

```
PM> Install-Package xunit.performance.api -Version 1.0.0-beta-build0020 -Source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
The 'Source' parameter is not respected for the transitive package management based project(s) Unit Tests\JohnZabroski.Xunit.Performance.Runner. The enabled sources in your NuGet configuration will be used. 
Restoring packages for D:\Source\JohnZabroski.Xunit.Performance.Runner\JohnZabroski.Xunit.Performance.Runner.csproj...
Installing NuGet package xunit.performance.api 1.0.0-beta-build0020.
Committing restore...
Generating MSBuild file D:\Source\JohnZabroski.Xunit.Performance.Runner\obj\JohnZabroski.Xunit.Performance.Runner.csproj.nuget.g.props.
Writing lock file to disk. Path: D:\Source\JohnZabroski.Xunit.Performance.Runner\obj\project.assets.json
Restore completed in 220.82 ms for D:\Source\JohnZabroski.Xunit.Performance.Runner\JohnZabroski.Xunit.Performance.Runner.csproj.
Successfully installed 'CommandLineParser.NS20 2.3.1' to JohnZabroski.Xunit.Performance.Runner
Successfully installed 'MarkdownLog.NS20 0.10.1' to JohnZabroski.Xunit.Performance.Runner
Successfully installed 'Microsoft.Diagnostics.Tracing.TraceEvent 2.0.5' to JohnZabroski.Xunit.Performance.Runner
Successfully installed 'System.IO 4.1.0' to JohnZabroski.Xunit.Performance.Runner
Successfully installed 'System.Reflection 4.1.0' to JohnZabroski.Xunit.Performance.Runner
Successfully installed 'System.Reflection.Primitives 4.0.1' to JohnZabroski.Xunit.Performance.Runner
Successfully installed 'System.Runtime 4.1.0' to JohnZabroski.Xunit.Performance.Runner
Successfully installed 'System.Runtime.Loader 4.0.0' to JohnZabroski.Xunit.Performance.Runner
Successfully installed 'System.Text.Encoding 4.0.11' to JohnZabroski.Xunit.Performance.Runner
Successfully installed 'System.Threading.Tasks 4.0.11' to JohnZabroski.Xunit.Performance.Runner
Successfully installed 'xunit 2.4.0' to JohnZabroski.Xunit.Performance.Runner
Successfully installed 'xunit.abstractions 2.0.2' to JohnZabroski.Xunit.Performance.Runner
Successfully installed 'xunit.analyzers 0.10.0' to JohnZabroski.Xunit.Performance.Runner
Successfully installed 'xunit.assert 2.4.0' to JohnZabroski.Xunit.Performance.Runner
Successfully installed 'xunit.core 2.4.0' to JohnZabroski.Xunit.Performance.Runner
Successfully installed 'xunit.extensibility.core 2.4.0' to JohnZabroski.Xunit.Performance.Runner
Successfully installed 'xunit.extensibility.execution 2.4.0' to JohnZabroski.Xunit.Performance.Runner
Successfully installed 'xunit.performance.api 1.0.0-beta-build0020' to JohnZabroski.Xunit.Performance.Runner
Successfully installed 'xunit.performance.core 1.0.0-beta-build0020' to JohnZabroski.Xunit.Performance.Runner
Successfully installed 'xunit.performance.execution 1.0.0-beta-build0020' to JohnZabroski.Xunit.Performance.Runner
Successfully installed 'xunit.performance.metrics 1.0.0-beta-build0020' to JohnZabroski.Xunit.Performance.Runner
Successfully installed 'xunit.runner.utility 2.4.0' to JohnZabroski.Xunit.Performance.Runner
Executing nuget actions took 302.4 ms
Time Elapsed: 00:00:01.4811947
PM> 
```

**To Be Clear**, this is a bug.  Do not just close this. The issue is that the nupkg has the wrong dependency.  The issue is specifically that the csproj for xunit.performance.metrics has a PackageReference that looks up the version based on https://github.com/Microsoft/xunit-performance/blob/407bec95b4a7649b667d670f0dd19a99c36df1ae/src/version.props#L3

**Comment by jzabroski** [comment]
@brianrob  @ViktorHofer  Is this project left for dead?   If so, what do you folks now use for microbenchmarking?  BenchmarkDotNet?

**Comment by ViktorHofer** [comment]
> what do you folks now use for microbenchmarking? BenchmarkDotNet?

As I'm not the owner of that repository I can't comment on that. Regarding what tooling we use for microbenchmarking, we recently switched from xunit-performance to BenchmarkDotNet in corefx.

**Comment by jzabroski** [comment]
Thanks @ViktorHofer - can I ask if there are any features xunit-performance has that BenchmarkDotNet does not?

It looks like some of the same bugs plague both frameworks.

**Comment by ViktorHofer** [comment]
I recommend using BenchmarkDotNet. If you need any features that are not in it, ping @adamsitnik or create an issue in their repo.

**Comment by jzabroski** [comment]
It would be ideal to use both.  Xunit.Performance should really just be a shit for plugging in a benchmarking framework, as opposed to the whole kitchen sink.  See my comments on #260 as an example of how Xunit.Performance is not architected correctly from a Xunit stylistic standpoint.

**Comment by brianrob** [comment]
@jzabroski, to answer your question, the .NET team (which maintains xunit-performance) is in the process of switching to use BenchmarkDotNet so that we can consolidate on a single benchmarking harness rather than maintaining two that do roughly the same things.  I suspect that once this is done, we are likely to either archive this repo or maintain it as is so that it can be used by the community as is.

To answer your question on feature set - there is a good amount of overlap with a few things unique to each harness.  For the most part, anything that we need from xunit-performance is being added to BenchmarkDotNet either at its core or using its plugin model.

**Comment by jzabroski** [comment]
@brianrob  Thanks a ton... after seeing how feature rich BenchmarkDotNet truly is, I'm not really looking back. It would be nice if someone adds the capability to do xunit-performance style tests, as I think it's a lot nicer for certain kinds of tests.  In general, I've always been inspired by Fixie for its pluggability as far as test frameworks go, but it never really caught on in .NET because it was "too configurable" (IMHO). - People found learning how to test code hard enough, so having lots of different options in set-up, teardown, etc. really confused people.

**Comment by brianrob** [comment]
Closing prior to archive.
