### ISSUE TITLE
Unable to install the package

### ISSUE THREAD

**Issue by skironDotNet** [Microsoft/xunit-performance#277]
I was trying to install using PM command as provided here https://dotnet.myget.org/feed/dotnet-core/package/nuget/xunit.performance.api

**Install-Package : NU1101: Unable to find package xunit.performance.api. No packages exist with this id in source(s): Local**

Then downloaded it and placed as local package

![image](https://user-images.githubusercontent.com/2981715/82059621-e5e78f80-968b-11ea-8488-96fb8f603725.png)

**Comment by brianrob** [comment]
Closing prior to archive.
