### ISSUE TITLE
Perf runner ETW tracing insufficient system resources

### ISSUE THREAD

**Issue by ianhays** [Microsoft/xunit-performance#79]
I've been getting the following error frequently:

```
 Copyright (C) 2015 Microsoft Corporation.

  Discovering tests for D:\git\corefx\bin\tests\Windows_NT.AnyCPU.Release\System.IO.FileSystem.Tests\dnxcore50\System.IO.FileSystem.T
  ests.dll.
  Discovered a total of 6 tests.
  Creating output directory: .
  Starting ETW tracing. Logging to .\latest-perf-build
EXEC : warning : Insufficient system resources exist to complete the requested service. (Exception from HRESULT: 0x800705AA) [D:\git\
corefx\src\System.IO.FileSystem\tests\System.IO.FileSystem.Tests.csproj]
  The previous error was converted to a warning because the task was called with ContinueOnError=true.
     at Microsoft.ProcessDomain.ProcDomain.<ExecuteAsync>d__26`1.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at Microsoft.Xunit.Performance.ETWLogging.<StartAsync>d__4.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at Microsoft.Xunit.Performance.Program.StartTracing(IEnumerable`1 tests, String pathBase)
     at Microsoft.Xunit.Performance.ProgramCore.RunTests(IEnumerable`1 tests, String runnerHost, String runnerCommand, String runnerA
  rgs, String runId, String outDir)
     at Microsoft.Xunit.Performance.ProgramCore.Run(String[] args)
```

While running the tests on Windows. I believe the issue is caused by my workflow:
- Start running the tests
- Tests hang indefinitely for some reason (I'm not writing infinite loops in my tests so there must be something else wrong here too, but I haven't yet discerned what).
- Pass a CTRL-C to the runner to stop it

ISSUE: The test directory can not be deleted due to the ETW.user file. 

After doing force stopping a few times, the runner will fail with the above error "Insufficient System Resources" and a complete system restart is required to enable me to run my tests again.

I assume this error has something to do with ETW files not being properly cleaned up when I CTRL-C the program, but google/StackOverflow gave no working solution to manually do it after the fact.

**Comment by ianhays** [comment]
@ericeil

**Comment by vancem** [comment]
An ETW session is one of the few things that live beyond the process that started it.    While the TraceEventSession class that is being used to open a ETW session has a destructor that will stop it by default, it can only do this if the destructor is called. 

Thus it is a good idea that anything with a TraceEventSession have a control-C handler that causes sessions to be disposed.   

TraceEventSession also has default logic that notices that if you are creating an existing session, it will close that existing session silently before opening the new one (you have to explicitly say you want to 'attach' if you wanted to open the existing session).   Thus things will tend to 'clean up' if you run the harness again, but you can have problems with open files etc in the mean time.

The upshot of all this, is to put in a Ctrl-C handler in the harness that causes the dispose.  The TraceEvent samples all do this so you can use them as a template if desired.

**Comment by ericeil** [comment]
The ETW session is owned by a separate process from the test harness, partly for this reason.  That process monitors for the death of the test harness, and is supposed to stop logging in that case.  It's possible that there are cases where the logger process gets terminated early, though.  Maybe we need to add an explicit Ctrl-C handler to the logger process, as @vancem suggests.

@ianhays, when you find yourself in this situation, the easiest way to recover is usually to reboot.

**Comment by ericeil** [comment]
Somehow the logic I mentioned, which monitors for xunit.performance.run's termination, wasn't hooked up any more.  I've pushed build 19 with the fix.
