### ISSUE TITLE
Deadlock when failing to deserialize a CrossDomainInvokeRequest

### ISSUE THREAD

**Issue by swgillespie** [microsoft/xunit-performance#99]
This is an interesting issue that I encountered when loading a custom performance metric that depended on a version of TraceEvent that was different that the one that the Logger process depended upon. In my case, when deserializing a CrossDomainInvokeRequest, an exception is thrown by the runtime for the assembly version mismatch which is propegated [here](https://github.com/Microsoft/xunit-performance/blob/master/src/procdomain/ProcDomain.cs#L142):

``` csharp
while ((parentMessage = await ReadNextRequestAsync()) != null)
{
    Task throwaway = HandleInvokeRequest(parentMessage);
}
```

Since the faulted task is awaited, it continues to unwind to [here](https://github.com/Microsoft/xunit-performance/blob/master/src/procdomain/ProcDomain.cs#L134):

``` csharp
var throwaway = ListenToParentDomainAsync();
```

where the task is never awaited, so the exception stops propagating. At this point, the child procdomain is waiting to be unloaded, but it will never be unloaded because `ListenToParentDomainAsync` unwound past the call to `this.Unload()` and is no longer listening to the parent domain. Meanwhile, the parent domain is waiting for a response from the child domain, which will never come (since it's not listening).

Simple repro:
1. Insert an exception [here](https://github.com/Microsoft/xunit-performance/blob/master/src/procdomain/CrossDomainInvokeRequest.cs#L32) so that this method begins to unwind.
2. Run a test suite as normal. The test runner gets stuck waiting for the trace to begin:

```
xunit.performance Console Runner (64-bit .NET 4.0.30319.42000)
Copyright (C) 2015 Microsoft Corporation.

Creating output directory: .
Discovering tests for C:\Users\segilles\Documents\Visual Studio 2015\Projects\Microsoft.Performance.GC\Microsoft.Performance.GC.Tests\bin\Debug\Microsoft.Performance.GC.Tests.dll.
Discovered a total of 1 tests.
Starting ETW tracing. Logging to .\Crash.etl
```

It will never progress past this point because it's waiting on the child procdomain which is partially faulted.

I looked into fixing this but there are a couple factors that make this tricky. 
1. Allowing the child procdomain to die via `async void` is not good because it leaks a ETW session in the Logger process, which is unacceptable.
2. Allowing the child procdomain to immediately unload on a fault causes the parent procdomain to wait forever on a response, still deadlocking.

Perhaps it would be possible to introduce a sort of protocol where the child procdomain could inform its parent (or vice versa) that it has faulted and will no longer respond to messages? Unfortunately, the scenario that would cause someone to run into this issue is probably quite common - the version mismatch in TraceEvent.

**Comment by brianrob** [comment]
Closing prior to archive.
